name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    run-on: ubuntu-latest	# Typo: should be runs-on
    need: [build]  # Typo: should be needs
    steps:
      - name: Install dependencies
        run: npm install
        
      - uses: actions/checkout@v3
      
      - name: Run tests  
        run: npm test
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
  build:
    runs-on: ubuntu-latest
    needs: [setup]  # Redundant dependency - setup is already a dependency of lint
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment
        run: echo "Setting up environment" 